### ISSUE TITLE
Organize patterns hierarchically

### ISSUE THREAD

**Issue by agryson** [appplemac/cooking-patterns#10]
The current organization of patterns by meal course (dessert, entrée etc.) is inappropriate for many patterns:
- Salad can be an entrée, appetizer, main meal or side dish. Fruit salad could even be a dessert

I suggest organizing patterns hierarchically from high level pattern to lower level patterns rather than by course or cooking methods.

e.g. : 
- Sandwich
  - Open Sandwich
    - Tartine
  - Closed Sandwich
    - Club Sandwich

Maybe this is too constraining and should change form, perhaps cooking method would be more appropriate? Or primary food group? Or a flat hierarchy that uses tags and relative links instead?

**Comment by navarr** [comment]
* Sandwich
 * Open Sandwich
   * Tartine
 * Closed Sandwich
   * Club Sandwich

**Comment by agryson** [comment]
Thanks @navarr , posted issue from app and messed up indenting

**Comment by appplemac** [comment]
I definitely agree – keeping a flat structure will not result in additional legibility. I like the hierarchical organisation you propose. One of the examples of such classification is [this recipe finder](http://www.foodandwine.com/recipe-finder/dish-types), with which I partially disagree but it’s a great head start.

I think we just might adopt that one for the moment.

**Comment by agryson** [comment]
Looks good, though I'd put hamburger under sandwich. ☺

**Comment by appplemac** [comment]
@agryson Careful with that :smile: 

See ac62eb33f7a2b171cf4bc6fa370da696a3469b9b

**Comment by appplemac** [comment]
And also 0172d1c0feb573303a220a47e3284d8b46226567, as I cannot check in the entire set of empty directories into this repo.
